version: "3.1"

services:
  catalogodiscos:
    image: oliveiragustavo/front-production:3.0
    ports:
      - "8080:8080"
    networks: 
      - production-network

  catalogodiscosback:
    image: oliveiragustavo/back-production:3.0
    ports:
      - "8000:8000"
    networks: 
      - production-network

networks: 
  production-network:
    driver: bridge